### PR TITLE
immudb 5.5.0 config update

### PR DESCRIPTION
**Pull request by pranavv0**
Change in immudb config.json as per v5.5.0  release. added table ogcaudit, auditing_consent, and auditing_dmp
added print statement in python script.

### CODE REVIEW

**Review by abhi4578 — COMMENTED** [review]
@pranavv0 was this tested with local new version (1.9Dom.2) immudb?

**Comment by pranavv0** [comment]
> @pranavv0 was this tested with local new version (1.9Dom.2) immudb?

yes it is now tested as per new images in docker env.

**Review by abhi4578 — APPROVED** [review]
LGTM

**Review by abhi4578 — APPROVED** [review]

**Review by abhi4578 — CHANGES_REQUESTED** [review]
Can you test it once with this configuration

**Comment by pranavv0** [comment]
> Can you test it once with this configuration

yest tested, its working.

**Review by abhi4578 — APPROVED** [review]

**Review by abhi4578 — APPROVED** [review]

**Pull request merged**
