### PR TITLE
ES autoscaler fix

### PR DESCRIPTION
**Pull request by karun-singh**
- fix rbac permissions
- fix helm upgrade command in es autoscale script

### CODE REVIEW

**Review by abhi4578 — APPROVED** [review]
LGTM, is it tested once end to end. trying bringing up new data nodes from inside autoscaler container

**Comment by karun-singh** [comment]
> LGTM, is it tested once end to end. trying bringing up new data pods from inside autoscaler container?

Yes @abhi4578, it is tested.

**Comment by abhi4578** [comment]
Can u backport 4.5.0 branch also? @karun-singh

**Comment by karun-singh** [comment]
> Can u backport 4.5.0 branch also? @karun-singh

Yes, will do.

**Pull request merged**
