### PR TITLE
Docker software-update: Postgress version update to 14.4.0

### PR DESCRIPTION
**Pull request by pranavv0**
Updates:
1. image version from 11.14.0 to 14.4.0
2. Updates in Stack files
3. Updates in README
4. Enable TCP keepalive at postgres
5. Added pg_hpa.conf
6. removed auth_db_name from init-script

### CODE REVIEW

**Review by abhi4578 — CHANGES_REQUESTED** [review]
Need to add following content in pg_hba.conf to allow scram-sha256 authenticate
```
host     all             all             0.0.0.0/0               md5
host     all             all             ::/0                    md5
local    all             all                                     md5
host     all             all        127.0.0.1/32                 md5
host     all             all        ::1/128                      md5
host     all             all  	     0.0.0.0/0 		         scram-sha-256
```
where to mount pg_hba.conf - https://github.com/bitnami/containers/tree/main/bitnami/postgresql#modify-pg_hbaconf

**Comment by karun-singh** [comment]
> 4\. Enable TCP keepalive at postgres

Where is this change implemented?

**Comment by pranavv0** [comment]
> > 4. Enable TCP keepalive at postgres
> 
> Where is this change implemented?

https://github.com/pranavv0/iudx-deployment/blob/0c45ee75d4c356b03ebe10c60b5ace064cec7e4f/Docker-Swarm-deployment/single-node/postgres/postgres-stack.yaml#L32

**Comment by karun-singh** [comment]
> https://github.com/pranavv0/iudx-deployment/blob/0c45ee75d4c356b03ebe10c60b5ace064cec7e4f/Docker-Swarm-deployment/single-node/postgres/postgres-stack.yaml#L32

Okay, this change is already merged in master. That's why it isn't showing in this PR's changes.

**Comment by karun-singh** [comment]
@pranavv0 Also include the creation of `iudx_auth` db in the init script.

**Comment by abhi4578** [comment]
> @pranavv0 Also include the creation of `iudx_auth` db in the init script.

this db is not required to be created. Auth (AAA)  sever uses default postgres db. That  https://github.com/datakaveri/iudx-deployment/blob/8ff3c57fe81a57a3723c4de0a28c2845733ac831/Docker-Swarm-deployment/single-node/postgres/init-scripts/db-user-creation.sh#L13 needs to be removed in the init script.

Also either merge the master branch with this /rebase before closing pR

**Comment by abhi4578** [comment]
similarly at K8s deployment - https://github.com/datakaveri/iudx-deployment/blob/8ff3c57fe81a57a3723c4de0a28c2845733ac831/K8s-deployment/Charts/postgresql/init-scripts/db-user-creation.sh#L13 . and add ccomment that auth server uses default postgres db in both

**Pull request closed without merging**
