### PR TITLE
Added Jenkinsfile and auth.txt

### PR DESCRIPTION
**Pull request by THARAK-RAM1**

### CODE REVIEW

**Comment by karun-singh** [comment]
retest this please

**Comment by karun-singh** [comment]
retest this please

**Comment by karun-singh** [comment]
retest this please

**Comment by karun-singh** [comment]
retest this please

**Comment by karun-singh** [comment]
retest this please

**Comment by karun-singh** [comment]
retest this please

**Comment by abhi4578** [comment]
Can this be closed. if it can be close it @THARAK-RAM1

**Pull request closed without merging**
